/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base_Datos.formularios;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author HP
 */
public class Frm_menu_Principla extends javax.swing.JFrame {

    /**
     * Creates new form Frm_menu_Principla
     */
    pnl_Alta_alum alumno= new pnl_Alta_alum();
    pnl_Buscar_Alumno buscar = new pnl_Buscar_Alumno();
    pnl_Eliminar_Alumno eliminar = new pnl_Eliminar_Alumno();
    pnl_Modificar_Alumno modificar = new pnl_Modificar_Alumno();
    
    CardLayout vista;
    public Frm_menu_Principla() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        vista=(CardLayout)pnl_vista_principal.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JToggleButton();
        btnAlta = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        btnmodificar = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JButton();
        pnl_vista_principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Menu del sistema");

        btnBuscar.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Base_Datos/imagenes/Buscar.jpeg"))); // NOI18N
        btnBuscar.setText("buscar alumno");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAlta.setBackground(new java.awt.Color(204, 204, 204));
        btnAlta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Base_Datos/imagenes/Alta.jpeg"))); // NOI18N
        btnAlta.setText("Registro de alumno");
        btnAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAlta.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Base_Datos/imagenes/Eliminar.jpeg"))); // NOI18N
        btnEliminar.setText("Eliminar alumno");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnmodificar.setBackground(new java.awt.Color(204, 204, 204));
        btnmodificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Base_Datos/imagenes/Modificar.jpeg"))); // NOI18N
        btnmodificar.setText("Modificar de alumno");
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Base_Datos/imagenes/Cerrar.jpeg"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(btnAlta)
                .addGap(43, 43, 43)
                .addComponent(btnmodificar)
                .addGap(39, 39, 39)
                .addComponent(btnEliminar)
                .addGap(27, 27, 27)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(3, 3, 3))
        );

        pnl_vista_principal.setBackground(new java.awt.Color(204, 0, 153));
        pnl_vista_principal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        if(btnmodificar.isSelected()){
        pnl_vista_principal.add(modificar,  "Modificar");
        vista.show(pnl_vista_principal, "Modificar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        
        btnBuscar.setEnabled(false);
         btnEliminar.setEnabled(false);
         btnAlta.setEnabled(false);
        btnmodificar.setBackground(Color.white);
        }else{
             pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
               btnBuscar.setEnabled(true);
         btnEliminar.setEnabled(true);
         btnAlta.setEnabled(true);
         btnmodificar.setBackground(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         if(btnEliminar.isSelected()){
        pnl_vista_principal.add(eliminar,  "Eliminar");
        vista.show(pnl_vista_principal, "Eliminar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        
          btnBuscar.setEnabled(false);
         btnmodificar.setEnabled(false);
         btnAlta.setEnabled(false);
        btnEliminar.setBackground(Color.white);
        
        }else{
             pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
               btnBuscar.setEnabled(true);
         btnmodificar.setEnabled(true);
         btnAlta.setEnabled(true);
         btnEliminar.setBackground(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
                 if(btnBuscar.isSelected()){
        pnl_vista_principal.add(buscar,  "Buscar");
        vista.show(pnl_vista_principal, "Buscar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        
           btnEliminar.setEnabled(false);
         btnmodificar.setEnabled(false);
         btnAlta.setEnabled(false);
        btnBuscar.setBackground(Color.white);
        
        }else{
             pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
               btnEliminar.setEnabled(true);
         btnmodificar.setEnabled(true);
         btnAlta.setEnabled(true);
         btnBuscar.setBackground(new Color(204,204,204));
                 }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        if(btnAlta.isSelected()){
            
        
        pnl_vista_principal.add( alumno,"Alta");
        vista.show(pnl_vista_principal, "Alta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
        btnBuscar.setEnabled(false);
         btnEliminar.setEnabled(false);
         btnmodificar.setEnabled(false);
        btnAlta.setBackground(Color.white);
        alumno.limpiar();
        
        }else{
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
               btnBuscar.setEnabled(true);
         btnEliminar.setEnabled(true);
         btnmodificar.setEnabled(true);
         btnAlta.setBackground(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_Principla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_Principla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_Principla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_menu_Principla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_menu_Principla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlta;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl_vista_principal;
    // End of variables declaration//GEN-END:variables
}
